name: ESLint

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "develop" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.57.0

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.cjs
          --ext .js,.jsx,.ts,.tsx
      - run: npm run test --if-present
      - run: npm run build --if-present
